torchrun --nproc_per_node=1 fine-tune.py  \
        --model_name_or_path ~/projects/aliendao/llama2 \
        --data_dir /home/yujin-wa20/projects/LongLoRA/data/redpajama_1t_sample_8192 \
        --bf16 True \
        --output_dir out/       \
        --cache_dir out_cache/ \
        --model_max_length 8192 \
        --use_flash_attn True \
        --low_rank_training True \
        --num_train_epochs 1  \
        --per_device_train_batch_size 1     \
        --per_device_eval_batch_size 2     \
        --gradient_accumulation_steps 8     \
        --evaluation_strategy "no"     \
        --save_strategy "steps"     \
        --save_steps 200     \
        --save_total_limit 2     \
        --learning_rate 2e-5     \
        --weight_decay 0.0     \
        --warmup_steps 20     \
        --lr_scheduler_type "constant_with_warmup" \
        --logging_steps 1     \
        --tf32 True \
        --max_steps 200 \
        --deepspeed "ds_configs/stage2.json"